<?php
// * Scan all files and subfolders in theme files "__()"
function my_theme_get_translatable_strings($dir)
{
    $strings = array();
    $di = new RecursiveDirectoryIterator($dir);
    foreach (new RecursiveIteratorIterator($di) as $filename => $file) {
        if (is_file($filename)) {
            $file_contents = file_get_contents($filename);
            preg_match_all('/__\(([^)]+)\)/', $file_contents, $matches);
            foreach ($matches[1] as $match) {
                $strings[] = trim($match, "'\"");
            }
        }
    }
    return array_unique($strings);
}

// * Creating a translation file "pot"
function my_theme_generate_translation_file($dir, $filename, $domain)
{
    // * create file path
    $path = $dir . "/languages/" . $filename . ".pot";
    // * get text
    $strings = my_theme_get_translatable_strings($dir);
    // * open file
    $file = fopen($path, 'w');
    // * write
    fputs($file, "# " . $domain . " translation file\n");
    fputs($file, "# Generated by My Theme\n\n");
    foreach ($strings as $string) {
        fputs($file, "#: \n");
        fputs($file, "msgid \"" . $string . "\"\n");
        fputs($file, "msgstr \"\"\n\n");
    }
    // * close file
    fclose($file);
}

$dir = get_template_directory(); // * Theme home directory
$filename = 'my-theme'; // * POT file name
$domain = 'my-theme'; // * The theme's translation area

my_theme_generate_translation_file($dir, $filename, $domain);
